apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  labels:
    apps: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: mongodb
  template:
    metadata:
      name: mongo
      labels:
        apps: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-sec
                  key: root-username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-sec
                  key: root-password

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    apps: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
